---
# tasks file for setup_server
- name: Create devops group
  group:
    name: devops
    state: present

- name: Create devops user
  user:
    name: devops
    shell: /bin/bash
    group: devops

